apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: m-ecommerce
  labels:
    app: email-service
spec:
  selector:
    app: email-deployment
  ports:
    - protocol: TCP
      port: 5006
      targetPort: 5006