apiVersion: v1
kind: ConfigMap
metadata:
 name: mongodb-conf
 namespace: m-ecommerce
data:
 host: mongodb-service
 port: "27017"
---
apiVersion: v1
kind: Secret
metadata:
 name: organization-secret
 namespace: m-ecommerce
data:
 ORGANIZATION_PASSWORD: Y2xvdWQyMDIzCg==


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
  namespace: m-ecommerce
spec:
  selector:
    matchLabels:
      app: email-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: email-deployment
    spec:
      containers:
        - name: email-deployment
          image: asmaeel/email-microservice:1.5
          ports:
            - containerPort: 5006
              name: email-port
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongodb-conf
                  key: port
            - name: MONGO_URI
              value: "mongodb://mongodb-service/microservices"
            - name: RABBIT_MQ_URI
              value: "amqp://rabbitmq:5672"
            - name: ORGANIZATION_EMAIL
              value: "riad.elhajjaji@outlook.com"
            - name: organization-password
              valueFrom:
                secretKeyRef:
                  name: organization-secret
                  key: ORGANIZATION_PASSWORD
            